---
- name: Setting RADIUS Database
  hosts: db_host
  become: yes
  vars:
    - username: crafter
    - home: /home/crafter
    - raddb: '/root/raddb1'
  tasks:
    - name: load site definition
      ansible.builtin.include_vars:
        file: data.yaml
        name: site_def
    - name: Copy FreeRADIUS Schema
      ansible.builtin.copy:
        src: "config/db_setup/schema.sql"
        dest: "{{ raddb }}/schema.sql"
        owner: crafter
        group: crafter
        follow: false
        
    - name: Generate Database Setup Script
      ansible.builtin.template:
        src: "config/db_setup/mysql.j2"
        dest: "{{ raddb }}/radiusdb_setup.sql"
        owner: crafter
        group: crafter
        follow: false
    - name: Create radius database
      ansible.builtin.shell: |
        mysql < "{{ raddb }}/radiusdb_setup.sql"
