---
- name: Install FreeRADIUS
  hosts: radius
  become: yes
  tasks:
    - name: Install FreeRADIUS on Debian
      ansible.builtin.apt:
        name:
          - freeradius
          - freeradius-mysql
          - freeradius-utils 
        autoremove: yes
        force_apt_get: yes
        state: latest
        update_cache: yes
      when:
        - ansible_facts['os_family'] == "Debian"
        
    - name: Check FreeRADIUS Installation
      ansible.builtin.shell: |
        freeradius -v
      when:
        - ansible_facts['os_family'] == "Debian"

    - name: Install FreeRadius on CentOS
      ansible.builtin.yum:
        enablerepo: elp-repo
        name:
          - freeradius
          - freeradius-utils
          - freeradius-mysql
        update_cache: yes
        state: latest
      when:
        - ansible_facts['os_family'] == "CentOS"

    - name: Check FreeRADIUS Installation
      ansible.builtin.shell: |
        radiusd -v
      when:
        - ansible_facts['os_family'] == "CentOS"

